# Generated by Django 4.0.7 on 2023-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='astatus',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
