# Generated by Django 4.0.7 on 2023-06-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Appoint List'},
        ),
        migrations.AlterModelOptions(
            name='medicinal',
            options={'verbose_name_plural': 'Medicinal'},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name_plural': 'Medicinecategory'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name_plural': 'Prescription'},
        ),
    ]
