# Generated by Django 3.2.18 on 2023-05-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20230516_1627'),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='hospital.patient'),
        ),
    ]
