# Generated by Django 3.2.19 on 2023-06-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_rename_dec_paymentcategory_desc'),
        ('customer', '0006_remove_prescription_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_dr_gives_prescription', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patient_receives_prescription', to='hospital.patient'),
        ),
    ]
