# Generated by Django 3.2.19 on 2023-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20230611_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='advice',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='history',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='note',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
