# Generated by Django 4.0.7 on 2023-05-16 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_category_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_patient', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.paymentcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_for_hospital', to=settings.AUTH_USER_MODEL),
        ),
    ]
