<<<<<<< HEAD
# Generated by Django 3.2.19 on 2023-06-12 18:09
=======
# Generated by Django 4.0.7 on 2023-06-12 10:15
>>>>>>> c17157e0fb4d8440b7c0c7d14ace22ca471eab4a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
