# Generated by Django 4.0.7 on 2023-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_region_options_region_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='hospital',
        ),
    ]
