# Generated by Django 4.0.7 on 2023-05-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmmauth', '0002_passcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_hospital',
        ),
    ]
