# Generated by Django 4.0.7 on 2023-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmauth', '0002_user_is_pha_user_is_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
