# Generated by Django 4.0.7 on 2023-07-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmauth', '0004_user_hospital_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(null=True, upload_to='hospital_logo/'),
        ),
    ]
