# Generated by Django 3.2.19 on 2023-05-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('bloodgroup', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('weight', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('age', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default='None', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
