# Generated by Django 4.0.7 on 2023-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadthrecord',
            old_name='status',
            new_name='addres',
        ),
        migrations.RemoveField(
            model_name='deadthrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='desc',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='title',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
