# Generated by Django 4.0.7 on 2023-06-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.AddField(
            model_name='province',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_province', to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_diff_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
