# Generated by Django 3.2.19 on 2023-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
