# Generated by Django 4.0.7 on 2023-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name_plural': 'Treatment Log'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatmentstatus',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
