# Generated by Django 4.0.7 on 2023-05-18 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_auto_20230516_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctor_name', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_belogs_to_hospital_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
