# Generated by Django 3.2.19 on 2023-05-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_message_about_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patientid',
        ),
    ]
