# Generated by Django 3.2.19 on 2023-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_donor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
