# Generated by Django 3.2.19 on 2023-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20230523_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
