# Generated by Django 4.0.7 on 2023-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_status_deadthrecord_addres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childbirth',
            name='patient',
        ),
        migrations.AddField(
            model_name='childbirth',
            name='race',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childbirth',
            name='title',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='race',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
