# Generated by Django 4.0.7 on 2023-05-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
    ]
