# Generated by Django 4.0.7 on 2023-06-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_treatment_log', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment_name', to='hospital.patient'),
        ),
    ]
