# Generated by Django 4.0.7 on 2023-06-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_province_country_province_hospital_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
