# Generated by Django 4.0.7 on 2023-06-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_treatment_options_treatment_treatmentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treatmentstatus',
            new_name='tstatus',
        ),
    ]
