# Generated by Django 4.0.7 on 2023-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_treatment_dr_alter_treatment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcategory',
            name='desc',
        ),
        migrations.AddField(
            model_name='paymentcategory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
