# Generated by Django 3.2.19 on 2023-05-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_childbirth_patient_childbirth_race_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadthrecord',
            old_name='addres',
            new_name='address',
        ),
    ]
