# Generated by Django 3.2.19 on 2023-06-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_patient_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
