# Generated by Django 4.0.7 on 2023-06-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_treatmentstatus_treatment_tstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatmentid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
