# Generated by Django 3.2.19 on 2023-05-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresource',
            name='date',
        ),
    ]
