# Generated by Django 4.0.7 on 2023-05-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_hospital_doctor_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='pname',
        ),
    ]
