# Generated by Django 4.0.7 on 2023-05-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanresource',
            name='date',
        ),
        migrations.AddField(
            model_name='humanresource',
            name='picture',
            field=models.ImageField(null=True, upload_to='employee_pictures/'),
        ),
        migrations.AddField(
            model_name='humanresource',
            name='signature',
            field=models.ImageField(null=True, upload_to='employee_signature/'),
        ),
    ]
