# Generated by Django 3.2.19 on 2023-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
