# Generated by Django 4.0.7 on 2023-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_admissionfees_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
