# Generated by Django 4.0.7 on 2023-05-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_hospital_pname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='province',
        ),
    ]
