# Generated by Django 4.0.7 on 2023-06-14 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_remove_paymentcategory_desc_paymentcategory_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patienttest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('status', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patient_test_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
