# Generated by Django 3.2.19 on 2023-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_addres_deadthrecord_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadthrecord',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='childbirth',
            name='status',
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='gender',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deadthrecord',
            name='lastname',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
