# Generated by Django 3.2.19 on 2023-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
