# Generated by Django 3.2.19 on 2023-05-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_humanresource_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresource',
            name='picture',
            field=models.ImageField(null=True, upload_to='doctors_pictures/'),
        ),
        migrations.AddField(
            model_name='humanresource',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humanresource',
            name='signature',
            field=models.ImageField(null=True, upload_to='doctors_signature/'),
        ),
        migrations.AlterField(
            model_name='humanresource',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
