# Generated by Django 4.0.7 on 2023-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_treatment_treatmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapreport',
            name='testid',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
