# Generated by Django 4.0.7 on 2023-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_lapreport_testid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='testid',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
