# Generated by Django 4.0.7 on 2023-06-14 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0005_patienttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_test_name', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_patient_test_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
