# Generated by Django 3.2.19 on 2023-06-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20230614_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blood',
            name='bloodgroup',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
