# Generated by Django 4.0.7 on 2023-08-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_admission_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='updated_at',
        ),
    ]
