# Generated by Django 3.2.19 on 2023-06-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20230603_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='departmentid',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
