# Generated by Django 4.0.7 on 2023-05-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_rename_pname_doctor_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
