# Generated by Django 4.0.7 on 2023-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_labresult_testid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatmentid',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
