# Generated by Django 4.0.7 on 2023-06-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patienttest_patient_alter_patienttest_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='remark',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
