# Generated by Django 3.2.19 on 2023-05-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctor_profile_alter_department_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='desc',
            new_name='departmentdesc',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='departmentname',
        ),
    ]
