# Generated by Django 4.0.7 on 2023-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_treatment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='pstate',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='desc',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dname',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='remark',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
