# Generated by Django 4.0.7 on 2023-05-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctor_profile_alter_department_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='date',
        ),
    ]
