# Generated by Django 4.0.7 on 2023-08-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_admission_discharge_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blood',
            options={'verbose_name_plural': 'Blood Bank'},
        ),
    ]
