# Generated by Django 3.2.19 on 2023-06-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_appointment_medicine_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dr',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
