# Generated by Django 4.0.7 on 2023-05-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type_sent',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
