# Generated by Django 4.0.7 on 2023-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_blood_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
