# Generated by Django 4.0.7 on 2023-05-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_email_type_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
