# Generated by Django 3.2.19 on 2023-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20230519_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospitalid',
        ),
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
