# Generated by Django 4.0.7 on 2023-06-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_treatment_pstate_alter_treatment_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
