# Generated by Django 4.0.7 on 2023-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_patienttest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='desc',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dname',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='remark',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
