# Generated by Django 4.0.7 on 2023-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='title',
            new_name='names',
        ),
        migrations.AddField(
            model_name='messages',
            name='phone',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
