# Generated by Django 4.0.7 on 2023-06-10 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0009_excategory_paymentcategory_payment_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excategory',
            new_name='Expensescategory',
        ),
    ]
