# Generated by Django 3.2.19 on 2023-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20230519_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitalid',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
