# Generated by Django 4.0.7 on 2023-06-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_treatment_desc_alter_treatment_dname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='payment',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
