# Generated by Django 4.0.7 on 2023-06-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_rename_excategory_expensescategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcategory',
            old_name='dec',
            new_name='desc',
        ),
    ]
