# Generated by Django 4.0.7 on 2023-07-06 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0010_rename_title_messages_names_messages_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakage', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('dayscount', models.CharField(blank=True, default='Pending', max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True)),
                ('created_at', models.DateField()),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_system_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fees',
            },
        ),
    ]
