# Generated by Django 4.0.7 on 2023-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_rename_dec_paymentcategory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
