# Generated by Django 4.0.7 on 2023-06-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_treatment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='visitdsc',
        ),
    ]
