# Generated by Django 4.0.7 on 2023-08-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_bloodpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpurchase',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_blood_purchase', to='hospital.patient'),
        ),
    ]
