# Generated by Django 4.0.7 on 2023-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='dayscount',
        ),
        migrations.AddField(
            model_name='fees',
            name='expireddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='paiddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
