# Generated by Django 4.0.7 on 2023-08-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_bloodpurchase_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpurchase',
            name='unitprice',
        ),
    ]
