# Generated by Django 4.0.7 on 2023-06-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_payment_visitdsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
    ]
