# Generated by Django 4.0.7 on 2023-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_remove_payment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='treatedby_dr',
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
