# Generated by Django 4.0.7 on 2023-09-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=11, null=True),
        ),
    ]
