# Generated by Django 4.0.7 on 2023-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_lapreport_labresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapreport',
            name='desc',
        ),
    ]
