# Generated by Django 4.0.7 on 2023-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_lapreport_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapreport',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
